### ISSUE TITLE
Put collectstatic dry run output somewhere nicer than /dev/null

### ISSUE THREAD

**Issue by stickywes** [dulaccc/heroku-buildpack-geodjango#10]
Sort of a feature request, I suppose, to improve UX/DX.

Having somewhere to look for build errors, such as something found during the collectstatic dry-run, would be really peachy.  I would've been able to figure out some deploy issues I was having much quicker if I had a build error logfile to reference.

**Comment by dulaccc** [comment]
Good idea, but this feature needs to be integrated in the [upstream repo](https://github.com/heroku/heroku-buildpack-python), did you opened an issue on the upstream repo too ?

**Comment by stickywes** [comment]
Sorry, I guess I was not clear.  I'm not talking about a general feature request,  I'm speaking directly about what I see as a problem with this build pack and how it handles output during build steps; explicitly the collectstatic behavior.

Instead of redirecting "collectstatic --dryrun" into /dev/null you should consider redirecting it into a log file; or any other similar steps explicitly done in this build-pack.

**Comment by dulaccc** [comment]
You were perfectly clear :) don't worry about that.
I was saying that I'm using the [exact same collect-static step](https://github.com/heroku/heroku-buildpack-python/blob/master/bin/steps/collectstatic#L23) as the original heroku python buildpack.

That's why I was suggesting that your comment is more pertinent for the [heroku python buildpack](https://github.com/heroku/heroku-buildpack-python/).

**Comment by stickywes** [comment]
Indeed, I think you're right!  I had assumed steps that seemed Django-specific were being handled by this fork, not the python buildpack.
